# -*- coding: utf-8 -*-
"""data Analysis part.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wto88H2iM6QbOpJGGm5BJQ0x80XqEA-M
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('/content/spotify_data.csv')

# Display first few rows
print(df.head())

# Show summary info
print(df.info())

# Describe numerical features
print(df.describe())

# Check for missing values
print(df.isnull().sum())

# Plot correlation heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

# Histograms of numerical features
df.hist(figsize=(15, 10), bins=30)
plt.suptitle('Feature Distributions')
plt.tight_layout()
plt.show()

# Boxplots to check for outliers
num_cols = df.select_dtypes(include='number').columns
plt.figure(figsize=(15, 12))
for i, col in enumerate(num_cols, 1):
    plt.subplot(4, 4, i)
    sns.boxplot(y=df[col])
    plt.title(f'Boxplot of {col}')
plt.tight_layout()
plt.show()

# Optional: Pairplot for selected features (slow for many columns)
# sns.pairplot(df[['danceability', 'energy', 'valence', 'tempo']])
# plt.show()

